[3.4] prevent borked req. files from failing pyside install

diff --git a/3.4/Dockerfile b/3.4/Dockerfile
--- a/3.4/Dockerfile
+++ b/3.4/Dockerfile
@@ -1,10 +1,10 @@
 FROM pymor/python:3.4
 MAINTAINER René Milk <rene.milk@wwu.de>
 
+RUN pip install --no-index -f https://pymor.github.io/wheels/ PySide && \
+    python -c 'import  PySide' || echo "import PySide failed"
 RUN /root/install_requirements.bash
 RUN $FENICS_HOME/build_and_test.bash
-
-ENV LD_LIBRARY_PATH=/usr/local/lib/python3.4/site-packages/PySide/:${LD_LIBRARY_PATH}
 
 VOLUME /src
 WORKDIR /src
