[pip] fix requirements install

diff --git a/3.4/Dockerfile b/3.4/Dockerfile
--- a/3.4/Dockerfile
+++ b/3.4/Dockerfile
@@ -15,10 +15,11 @@ RUN python -c 'import  PySide' || echo "import PySide failed"
 
 RUN pip install -U pip
 RUN pip install -U numpy
-RUN git clone https://github.com/pymor/pymor
-RUN pip install -r pymor/requirements.txt
-RUN pip install -r pymor/requirements-travis.txt
-RUN pip install -r pymor/requirements-optional.txt || echo "Some optional modules failed to install"
+RUN git clone https://github.com/pymor/pymor /tmp/pymor
+RUN pip install -r /tmp/pymor/requirements.txt
+RUN pip install -r /tmp/pymor/requirements-travis.txt
+RUN pip install -r /tmp/pymor/requirements-optional.txt || echo "Some optional modules failed to install"
+RUN rm -rf /tmp/pymor
 
 VOLUME /src
 WORKDIR /src
