adds installing pymor requirements in testing images

diff --git a/2.7/Dockerfile b/2.7/Dockerfile
--- a/2.7/Dockerfile
+++ b/2.7/Dockerfile
@@ -8,11 +8,18 @@ ENV DEBIAN_FRONTEND noninteractive
 RUN add-apt-repository -y ${FENICS_PPA}
 RUN aptitude update
 RUN aptitude install -y --without-recommends -q libslepc3.4.2-dev libhdf5-openmpi-dev  ${FENICS_PACKAGES}
+ENV DEBIAN_FRONTEND teletype
+
 RUN python -c 'import  dolfin' || echo "import dolfin failed"
 RUN pip install --no-index -f https://pymor.github.io/wheels/ pyside
 RUN python -c 'import  PySide' || echo "import PySide failed"
 
-ENV DEBIAN_FRONTEND teletype
+RUN pip install -U pip
+RUN pip install -U numpy
+RUN git clone https://github.com/pymor/pymor
+RUN pip install -r pymor/requirements.txt
+RUN pip install -r pymor/requirements-travis.txt
+RUN pip install -r pymor/requirements-optional.txt || echo "Some optional modules failed to install"
 
 VOLUME /src
 WORKDIR /src
diff --git a/3.6/Dockerfile b/3.6/Dockerfile
--- a/3.6/Dockerfile
+++ b/3.6/Dockerfile
@@ -6,6 +6,13 @@ RUN aptitude update
 
 ENV DEBIAN_FRONTEND teletype
 
+RUN pip install -U pip
+RUN pip install -U numpy
+RUN git clone https://github.com/pymor/pymor
+RUN pip install -r pymor/requirements.txt
+RUN pip install -r pymor/requirements-travis.txt
+RUN pip install -r pymor/requirements-optional.txt || echo "Some optional modules failed to install"
+
 VOLUME /src
 WORKDIR /src
 
